jenkinsci/kubernetes-cli-plugin

- .travis.yml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlTestBase.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/utils/FakeBearerTokenCredentialImpl.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/utils/UnsupportedCredential.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlRawWithContext.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlWithoutCaWithContext.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/mockedKubectlFailure.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/mockedKubectlWithEmptyCredential.groovy
Allow to specify the context to be used to configure `kubectl`
> Add support for contextName

- pom.xml
* Update parent POM
* Bump required core to 2.60.3 (already 1 year old)
* Replace dependency to httpclient lib by the corresponding library
plugin
> Depend on apache-httpcomponent plugin

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-clusterName.html
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlTestBase.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlRawWithCluster.groovy
The `--cluster` option is hard coded and can't be configured. This patch adds the `clusterName` parameter in pipelines.
> added support for clusterName option

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2019-10320
https://github.com/jenkinsci/credentials-plugin/releases
https://plugins.jenkins.io/credentials
https://wiki.jenkins.io/display/JENKINS/Credentials+Plugin
> Update credentials plugin from 2.1.7 to 2.1.19 (2.2.0) CVE-2019-10320

- README.md
namespace of the service account is required if it is not the 'default' namespace.
> non-default namespace

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
If the Jenkins workspace contains spaces, the path to the temporary files containing certificates have to be escaped when passed as parameter to a `kubectl` call.
> Fix escaping of certificate-authority parameter

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubeConfigExpander.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
Did not test this, but it made sense to do the cleanup outside of the multi-kube-config patch.
> remove duplicated KubeConfigExpander

- .travis.yml
- README.md
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
* Run tests for 1.16 and 1.17
* Drop tests for 1.10 and 1.11
> Add support for new kubectl versions and drop olders

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
This write the `kubectl` credentials back into the workspace instead of the temporary folder of the agent, that might actually not always be available from the execution environment.
Workaround for https://github.com/jenkinsci/kubernetes-cli-plugin/issues/49
Effectively reverts https://github.com/jenkinsci/kubernetes-cli-plugin/commit/73e2e1aac46295d74795706ac7ba0b49e9b045b7
> Write kubeconfig back in the workspace

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/GenericBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
Fixes the handling of raw `kubeconfig` files and the switch to a context.
Since 1.8.0 the switch is done after settings the cluster up which doesn't make much sense and doesn't reflect what's in the documentation. Also and unrelated to this fix, this PR prefixes log lines with the name of the plugin, and add a warning if a user configures a context that does not exist in the `kubeconfig` file.
Fixes https://github.com/jenkinsci/kubernetes-cli-plugin/issues/51
> Fix raw kubeconfig context switch

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapperTest.java
Should fix https://github.com/jenkinsci/kubernetes-cli-plugin/issues/59
> Fix UI job configuration for multiple credentials not being saved

- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineEchoPath.groovy
adds an explicit test to verify the content of the `KUBECONFIG` variable and ensure there is no extra new line character at the end
see https://github.com/jenkinsci/kubernetes-cli-plugin/issues/64
> add kubeconfig path test

- .travis.yml
- Jenkinsfile
- README.md
Support for Java 11 is coming:
* https://www.jenkins.io/doc/administration/requirements/upgrade-java-guidelines/
* https://www.jenkins.io/doc/administration/requirements/jenkins-on-java-11/
> enable tests on jdk11

- CHANGELOG.md
- README.md
- pom.xml
The kubernetes plugin is bringing in kubernetes-client-api in version 5.4.1 which breaks kubernetes-cli.
This PR could fix kubernetes-cli until https://github.com/jenkinsci/kubernetes-credentials-plugin/pull/35 is merged
> compile against kubernetes-client-api-5.4.1

- README.md
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlCredential.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterAuthTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineMissingCredentials.groovy
This PR allows the Kubernetes CLI Plugin to have `kubectl` fall back to a Pod's ServiceAccount, when the pipelines run inside Kubernetes.
The (kubernetes-credentials-plugin)[https://github.com/jenkinsci/kubernetes-credentials-plugin] provides a dedicated ServiceAccount kind of credentials but hose will soon not be usable anymore. Kubernetes has introduced rotation for those ServiceAccount token, and it appears that some service provider set a rather rotation lifetime (compared to previous infinity).
See:
* https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.21
* https://issues.jenkins.io/browse/JENKINS-68584
* https://issues.jenkins.io/browse/JENKINS-68557
> allow empty credentials for in-cluster Jenkins agents

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
We need to create an empty context if we want to be able to reference it as current context.
> fix incluster config without namespace

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/helpers/Version.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterAuthTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineConfigDump.groovy
This makes this plugin compatible with newer kubernetes-client version.
Downstream of 
* https://github.com/jenkinsci/kubernetes-client-api-plugin/pull/163
* https://github.com/jenkinsci/kubernetes-credentials-plugin/pull/36
> Upgrade kubernetes-client to 6.x

- pom.xml
We're pulling the dependency for testing, and versions under 1.17 have some vulnerabilities:
> Jenkins Docker Commons Plugin 1.17 and earlier does not sanitize the name of an image or a tag, resulting in an OS command execution vulnerability exploitable by attackers with Item/Configure permission or able to control the contents of a previously configured job's SCM repository.
> upgrade docker-commons to 1.18

- Jenkinsfile
- pom.xml
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
The Jenkins community is moving to Java 11: https://www.jenkins.io/blog/2022/12/14/require-java-11/
> don't build for Java 8 anymore

- Jenkinsfile
The Jenkins community already moved to Java 11, and preparation are required for Java 17: https://www.jenkins.io/blog/2022/12/14/require-java-11/
> run units with java 11 and 17

- Jenkinsfile
- pom.xml
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21 on Linux.
- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right …
> Update parent POM, test with Java 21

- .github/latest-version.sh
- Jenkinsfile
- README.md
Run tests on Kubernetes 1.28 and 1.29 as well. Manual tests are green for 1.28 already
> test on newest Kubernetes versions

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/CredentialsLister.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/helpers/DummyCredentials.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/helpers/DummyTokenCredentialImpl.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/helpers/UnsupportedCredentialImpl.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterAuthTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
1. update snakyaml library
- https://community.jenkins.io/t/getting-error-in-while-running-jenkins-job/9495/3
2. replace deprecated method
Execute exists test (It is not possible to create reproducible tests it's necessary an installation of jenkins with SnakeYaml 2.2.)
```[tasklist]
```
> update library and replace deprecate method

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/CredentialsLister.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlCredential.java
The Jenkins project recommends requiring HTTP POSTs on method that have side effects, or can harm the server when hammered, which perfectly makes sense. The security scanner issues warnings for the `doFillCredentialsIdItems` methods which are used to fill the credential list in the UI.
I don't expect the code being called to have any side-effect, but I see the community has adopted a mixed-posture for very similar code, oscillating between ignoring the security warning, or switching to POST. Better safe than sorry: requiring a POST is unlikely to cause any problem, let's just do it even if it's not necessary.
> requirePOST on doFillCredentialsIdItems
