jenkinsci/kubernetes-cli-plugin

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/CertificateHelper.java
- src/test/java/org/jenkinsci/plugins/kubernetes/credentials/kubeconfig/CertificateHelperTest.java
And don't wrap already wrapped certificates
> Add tests to CertificateHelper

- README.md
Copy and paste the example without the comma is driving me crazy.
> comma missing

- Jenkinsfile
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlWithCa.groovy
Decode the CA certificates as stated in the documentation.
I guess nobody use that feature
> Base64 Decode that CA certificates

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-namespace.html
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlMinimal.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/kubectlRawWithNamespace.groovy
Add support for namespaces as discussed in https://github.com/jenkinsci/kubernetes-cli-plugin/pull/22
> Add support for namespace

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
As suggested in https://issues.jenkins-ci.org/browse/JENKINS-56297
> Resolve environment variables in SERVER_URL

- .mvn/extensions.xml
- .mvn/maven.config
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
Subsumes #34 
Enables incrementals support on this repository
> Incrementals

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlTestBase.java
Switch to the latest version of `kubernetes-credentials-plugin` in order to remove the dependency to `kubectl` when setting the credentials.
> Get rid of kubectl

- README.md
fixes https://github.com/jenkinsci/kubernetes-cli-plugin/issues/41
> Add a quick implementation overview

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
The case where a user would switch to a non existent context was not tested and more broken that it should (it's a invalid combination of parameter).
This fixes it
> Fix creation of new contextes and add tests

- .travis.yml
- README.md
* v1.18.3
* v1.17.0 => v1.17.6
* v1.16.4 => v1.16.10
* v1.15.1 => v1.15.12
* v1.14.3 => v1.14.10
* v1.13.3 => v1.13.12
* v1.12.9 => v1.12.10
> test against newest versions

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/GenericBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterAuthTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
when multiple credentials are used, the currentContext will be set instead of being skipped.
> use kubernetes credentials 0.7.0

- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-caCertificate.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-clusterName.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-contextName.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-credentialId.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-namespace.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-serverUrl.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper/config.jelly
This doesn't work together with the Stapler generation on Windows
> remove symlinks

- pom.xml
put important information on top
> re-organization pom.xml

- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
Forcing the test script to execute in `bash` fails on Windows.
Removing the Shebang allows to test to run on both Linux and Windows
> remove shebang in tests and replace with platform specific command

- README.md
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
Fixes https://github.com/jenkinsci/kubernetes-cli-plugin/issues/73
Add environment variable interpolation for cluster, context and namespace.
> add environment interpolation for more parameters

- .travis.yml
- README.md
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/helpers/Version.java
* add kubectl 1.19
* remove kubectl 1.13, 1.14
* use latest versions 1.15, 1.16, 1.17, 1.18
> test against new kubectl versions

- .travis.yml
- README.md
* test against kubectl 1.20
* remove tests against kubectl 1.16
> test against 1.20, drop 1.16

- pom.xml
for better support of OpenShift
> bump kubernetes-credentials to 0.8.0

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/CredentialsLister.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlCredential.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStepTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlCredentialTest.java
> limit credentials returned when no ancestor is provided

- Jenkinsfile
- README.md
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineConfigDump.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeCredentialsPipelineAndServer.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeCredentialsPipelineAndUsernames.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeCredentialsPipelineConfigDump.groovy
* improve pipeline to test against combinations of platform/jdk/kubectl
* make integration tests work on Windows
> Move from Travis to Jenkins CI

- Jenkinsfile
See https://kubernetes.io/releases/
> stop testing EOL versions

- README.md
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/GenericBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterFactory.java
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildStep/help-restrictKubeConfigAccess.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlBuildWrapper/help-restrictKubeConfigAccess.html
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/KubectlCredential/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapper/config.jelly
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/MultiKubectlBuildWrapperTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterAuthTest.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineConfigPermissionsDefault.groovy
- src/test/resources/org/jenkinsci/plugins/kubernetes/cli/withKubeConfigPipelineConfigPermissionsRestrictedRead.groovy
Prevent Helm from displaying warnings: https://github.com/jenkinsci/kubernetes-cli-plugin/issues/76
> add support for making kubeconfig only accessible by owner

- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/KubectlIntegrationTest.java
Fixes https://github.com/jenkinsci/kubernetes-cli-plugin/issues/98
> track credential usage

- .github/latest-version.sh
- Jenkinsfile
- README.md
Test on Kubernetes 1.25 and 1.26
> test on new kubectl versions

- pom.xml
- src/main/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriter.java
- src/test/java/org/jenkinsci/plugins/kubernetes/cli/kubeconfig/KubeConfigWriterBuilderTest.java
* kubernetes-client-api 6.8.1
* raise jenkins requirement to 2.401.1
* compatibility fixes
```[tasklist]
```
> Update kubernetes dependencies

- .github/workflows/cd.yaml
- .mvn/maven.config
https://www.jenkins.io/doc/developer/publishing/releasing-cd/
> add releasing cd
